include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Additional good readability & safety rules
    always_use_package_imports: true
    prefer_single_quotes: true
    prefer_final_locals: true
    avoid_print: true
    avoid_unnecessary_containers: true
    unnecessary_null_checks: true
    require_trailing_commas: true

formatter:
  trailing_commas: preserve

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

  errors:
    invalid_override_of_non_virtual_member: error
    invalid_annotation_target: ignore

    # make const warnings flexible
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_single_quotes: ignore
